/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_KHashIv */

#ifndef _Included_org_jamruby_mruby_KHashIv
#define _Included_org_jamruby_mruby_KHashIv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_KHashIv
 * Method:    n_khExist
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jamruby_mruby_KHashIv_n_1khExist
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_KHashIv
 * Method:    n_khGet
 * Signature: (JJ)Lorg/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_org_jamruby_mruby_KHashIv_n_1khGet
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_KHashIv
 * Method:    n_khPut
 * Signature: (JJLorg/jamruby/mruby/Value;)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_KHashIv_n_1khPut
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_jamruby_mruby_KHashIv
 * Method:    n_khSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_KHashIv_n_1khSize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
