/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_RBasic */

#ifndef _Included_org_jamruby_mruby_RBasic
#define _Included_org_jamruby_mruby_RBasic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_RBasic
 * Method:    n_getValueType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_RBasic_n_1getValueType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_RBasic
 * Method:    n_getColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_RBasic_n_1getColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_RBasic
 * Method:    n_getFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_RBasic_n_1getFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_RBasic
 * Method:    n_getRClass
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_RBasic_n_1getRClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_RBasic
 * Method:    n_getGCNext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_RBasic_n_1getGCNext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
