/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crimsonwoods_android_libs_jamruby_mruby_MRuby */

#ifndef _Included_crimsonwoods_android_libs_jamruby_mruby_MRuby
#define _Included_crimsonwoods_android_libs_jamruby_mruby_MRuby
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1open
  (JNIEnv *, jclass);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_loadIrep
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1loadIrep
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_parseString
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1parseString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_parseFile
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1parseFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_generateCode
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1generateCode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_run
 * Signature: (JJLcrimsonwoods/android/libs/jamruby/mruby/Value;)Lcrimsonwoods/android/libs/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1run
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_defineGlobalConst
 * Signature: (JLjava/lang/String;Lcrimsonwoods/android/libs/jamruby/mruby/Value;)V
 */
JNIEXPORT void JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1defineGlobalConst
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_arrayNew
 * Signature: (J)Lcrimsonwoods/android/libs/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1arrayNew
  (JNIEnv *, jclass, jlong);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_arrayPush
 * Signature: (JLcrimsonwoods/android/libs/jamruby/mruby/Value;Lcrimsonwoods/android/libs/jamruby/mruby/Value;)V
 */
JNIEXPORT void JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1arrayPush
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_procNew
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1procNew
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_topSelf
 * Signature: (J)Lcrimsonwoods/android/libs/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1topSelf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_MRuby
 * Method:    n_p
 * Signature: (JLcrimsonwoods/android/libs/jamruby/mruby/Value;)Lcrimsonwoods/android/libs/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_MRuby_n_1p
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
