/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_KHashMt_KHMtIterator */

#ifndef _Included_org_jamruby_mruby_KHashMt_KHMtIterator
#define _Included_org_jamruby_mruby_KHashMt_KHMtIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_KHashMt_KHMtIterator
 * Method:    n_begin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_KHashMt_00024KHMtIterator_n_1begin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_KHashMt_KHMtIterator
 * Method:    n_end
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_KHashMt_00024KHMtIterator_n_1end
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_KHashMt_KHMtIterator
 * Method:    n_exist
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jamruby_mruby_KHashMt_00024KHMtIterator_n_1exist
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_KHashMt_KHMtIterator
 * Method:    n_next
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_KHashMt_00024KHMtIterator_n_1next
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_KHashMt_KHMtIterator
 * Method:    n_key
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_KHashMt_00024KHMtIterator_n_1key
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_KHashMt_KHMtIterator
 * Method:    n_value
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_KHashMt_00024KHMtIterator_n_1value
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
