/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_RData */

#ifndef _Included_org_jamruby_mruby_RData
#define _Included_org_jamruby_mruby_RData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_RData
 * Method:    n_getIv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_RData_n_1getIv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_RData
 * Method:    n_getType
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_RData_n_1getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_RData
 * Method:    n_getData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_RData_n_1getData
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
