/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crimsonwoods_android_libs_jamruby_mruby_RClass */

#ifndef _Included_crimsonwoods_android_libs_jamruby_mruby_RClass
#define _Included_crimsonwoods_android_libs_jamruby_mruby_RClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_RClass
 * Method:    n_getSuperClass
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_RClass_n_1getSuperClass
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
