/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_REnv */

#ifndef _Included_org_jamruby_mruby_REnv
#define _Included_org_jamruby_mruby_REnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_REnv
 * Method:    n_getMid
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_REnv_n_1getMid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_REnv
 * Method:    n_getCioff
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_REnv_n_1getCioff
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
