/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_RData_RDataType */

#ifndef _Included_org_jamruby_mruby_RData_RDataType
#define _Included_org_jamruby_mruby_RData_RDataType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_RData_RDataType
 * Method:    n_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jamruby_mruby_RData_00024RDataType_n_1getName
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
