/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_Value */

#ifndef _Included_org_jamruby_mruby_Value
#define _Included_org_jamruby_mruby_Value
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_Value
 * Method:    n_obj_id
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_Value_n_1obj_1id
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
