/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crimsonwoods_android_libs_jamruby_mruby_Pool */

#ifndef _Included_crimsonwoods_android_libs_jamruby_mruby_Pool
#define _Included_crimsonwoods_android_libs_jamruby_mruby_Pool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_Pool
 * Method:    n_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_Pool_n_1close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
