/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_KHashMt */

#ifndef _Included_org_jamruby_mruby_KHashMt
#define _Included_org_jamruby_mruby_KHashMt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_KHashMt
 * Method:    n_khExist
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jamruby_mruby_KHashMt_n_1khExist
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_KHashMt
 * Method:    n_khGet
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_KHashMt_n_1khGet
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_KHashMt
 * Method:    n_khPut
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_KHashMt_n_1khPut
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_KHashMt
 * Method:    n_khSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_KHashMt_n_1khSize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
