/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_RObject */

#ifndef _Included_org_jamruby_mruby_RObject
#define _Included_org_jamruby_mruby_RObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_RObject
 * Method:    n_getIv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_RObject_n_1getIv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_RObject
 * Method:    n_objIvGet
 * Signature: (JJJ)Lorg/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_org_jamruby_mruby_RObject_n_1objIvGet
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_RObject
 * Method:    n_objIvSet
 * Signature: (JJJLorg/jamruby/mruby/Value;)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_RObject_n_1objIvSet
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
