/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crimsonwoods_android_libs_jamruby_mruby_RString */

#ifndef _Included_crimsonwoods_android_libs_jamruby_mruby_RString
#define _Included_crimsonwoods_android_libs_jamruby_mruby_RString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_RString
 * Method:    n_getBuf
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_RString_n_1getBuf
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
