/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_RProc */

#ifndef _Included_org_jamruby_mruby_RProc
#define _Included_org_jamruby_mruby_RProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_RProc
 * Method:    n_getTargetClass
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_RProc_n_1getTargetClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_RProc
 * Method:    n_getEnv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_RProc_n_1getEnv
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
