/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_ParserState */

#ifndef _Included_org_jamruby_mruby_ParserState
#define _Included_org_jamruby_mruby_ParserState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_ParserState
 * Method:    n_getNerr
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_ParserState_n_1getNerr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_ParserState
 * Method:    n_getTree
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_ParserState_n_1getTree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_ParserState
 * Method:    n_getPool
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_ParserState_n_1getPool
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
