/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_MRuby */

#ifndef _Included_org_jamruby_mruby_MRuby
#define _Included_org_jamruby_mruby_MRuby
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_strNew
 * Signature: (JLjava/lang/String;)Lorg/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_org_jamruby_mruby_MRuby_n_1strNew
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_MRuby_n_1open
  (JNIEnv *, jclass);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_loadIrep
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_MRuby_n_1loadIrep
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_parseString
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_MRuby_n_1parseString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_parseFile
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_MRuby_n_1parseFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_generateCode
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_MRuby_n_1generateCode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_run
 * Signature: (JJLorg/jamruby/mruby/Value;)Lorg/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_org_jamruby_mruby_MRuby_n_1run
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_defineGlobalConst
 * Signature: (JLjava/lang/String;Lorg/jamruby/mruby/Value;)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_MRuby_n_1defineGlobalConst
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_arrayNew
 * Signature: (J)Lorg/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_org_jamruby_mruby_MRuby_n_1arrayNew
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_arrayPush
 * Signature: (JLorg/jamruby/mruby/Value;Lorg/jamruby/mruby/Value;)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_MRuby_n_1arrayPush
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_procNew
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_MRuby_n_1procNew
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_topSelf
 * Signature: (J)Lorg/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_org_jamruby_mruby_MRuby_n_1topSelf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_p
 * Signature: (JLorg/jamruby/mruby/Value;)Lorg/jamruby/mruby/Value;
 */
JNIEXPORT jobject JNICALL Java_org_jamruby_mruby_MRuby_n_1p
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_sym2name
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jamruby_mruby_MRuby_n_1sym2name
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_redirect_stdout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_MRuby_n_1redirect_1stdout
  (JNIEnv *, jclass);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_redirect_stderr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_MRuby_n_1redirect_1stderr
  (JNIEnv *, jclass);

/*
 * Class:     org_jamruby_mruby_MRuby
 * Method:    n_redirect_stdin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_MRuby_n_1redirect_1stdin
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
