/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_State */

#ifndef _Included_org_jamruby_mruby_State
#define _Included_org_jamruby_mruby_State
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_State
 * Method:    n_getIreps
 * Signature: (J)[Lorg/jamruby/mruby/Irep;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jamruby_mruby_State_n_1getIreps
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_State
 * Method:    n_getExc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jamruby_mruby_State_n_1getExc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_State
 * Method:    n_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_State_n_1close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
