/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crimsonwoods_android_libs_jamruby_mruby_AstNode */

#ifndef _Included_crimsonwoods_android_libs_jamruby_mruby_AstNode
#define _Included_crimsonwoods_android_libs_jamruby_mruby_AstNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_AstNode
 * Method:    n_getNodeType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_AstNode_n_1getNodeType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_AstNode
 * Method:    n_getCar
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_AstNode_n_1getCar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     crimsonwoods_android_libs_jamruby_mruby_AstNode
 * Method:    n_getCdr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_crimsonwoods_android_libs_jamruby_mruby_AstNode_n_1getCdr
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
