/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jamruby_mruby_GC */

#ifndef _Included_org_jamruby_mruby_GC
#define _Included_org_jamruby_mruby_GC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jamruby_mruby_GC
 * Method:    n_garbage_collect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_GC_n_1garbage_1collect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_GC
 * Method:    n_incremental_gc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_GC_n_1incremental_1gc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_GC
 * Method:    n_gc_arena_save
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jamruby_mruby_GC_n_1gc_1arena_1save
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jamruby_mruby_GC
 * Method:    n_gc_arena_restore
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_GC_n_1gc_1arena_1restore
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jamruby_mruby_GC
 * Method:    n_gc_mark
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_GC_n_1gc_1mark
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_GC
 * Method:    n_field_write_barrier
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_GC_n_1field_1write_1barrier
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jamruby_mruby_GC
 * Method:    n_write_barrier
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jamruby_mruby_GC_n_1write_1barrier
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
